// Bundles engine.ts + bot.ts into ../code-royale.ts (CodinGame takes one file).
import { readFileSync, writeFileSync } from "fs"
const dir = new URL(".", import.meta.url).pathname
const strip = s => s.replace(/^import[\s\S]*?from\s+"[^"]+"\s*\n/gm, "").replace(/^export /gm, "")
const engine = strip(readFileSync(dir + "engine.ts", "utf8"))
const bot = strip(readFileSync(dir + "bot.ts", "utf8"))
const head = "// @ts-nocheck-free bundle: unused engine exports are silenced below.\n" + "// 🎮 CodinGame Multiplayer - code-royale (generated by code-royale-tools/build.mjs: engine.ts + bot.ts)\n"
const tail = "\nvoid [OBSTACLE_GAP, parseAction, gameOver, renderInput]\n"
writeFileSync(dir + "../code-royale.ts", head + engine + "\n" + bot + tail)
console.log("written")
