// @ts-nocheck-free bundle: unused engine exports are silenced below.
// 🎮 CodinGame Multiplayer - code-royale (generated by code-royale-tools/build.mjs: engine.ts + bot.ts)
// Code Royale turn simulation, ported from the CodinGame referee
// (github.com/csj/code-royale: Referee.gameTurn, Characters.kt, Structures.kt,
// MapBuilding.fixCollisions, Vector2.kt). Player indices are the referee's: 0 = first player
// (red, spawns top-left), 1 = second (blue). The arithmetic and the loop orders mirror the Kotlin
// code so that float results match bit for bit.
//
// The game running on CodinGame is NOT exactly the GitHub source. Fitted on a recorded game
// (harness.ts, 160/160 turns exact with the hidden info known):
// - knights spawn with 25 HP (source: 30); giants 200 as in the source; archers unverified (45);
// - collision list order = p0 creeps, p0 queen, p1 creeps, p1 queen, sites (the source's
//   commented-out `allUnits()` variant), which matters for wall clamps and pushes;
// - spawned creep i starts at site + (1,-1), (-1,1), (1,1), (-1,-1) for both players
//   (source: + c*(i,i)), then moves 30 towards the enemy queen;
// - tower damage uses the distance from the site's centre (source subtracts the site radius);
// - structures act as the statement says: all towers (site order), dead creeps removed,
//   all barracks (spawns + collision fix), then all mines (source: one pass in site order).

const W = 1920
const H = 1000
const QUEEN_R = 30
const QUEEN_MASS = 10000
const QUEEN_SPEED = 60
const TOUCH = 5
const VISION = 300
const TOWER_HP_INITIAL = 200
const TOWER_HP_INCREMENT = 100
const TOWER_HP_MAXIMUM = 800
const GIANT_BUST_RATE = 80
const OBSTACLE_GAP = 90

// Structure types (as in the input): -1 none, 0 mine, 1 tower, 2 barracks
const NONE = -1
const MINE = 0
const TOWER = 1
const BARRACKS = 2
// Creep types (as in the input): 0 knight, 1 archer, 2 giant
const KNIGHT = 0
const ARCHER = 1
const GIANT = 2

// Per creep type: count, cost, speed, range, radius, mass, hp, buildTime
const C_COUNT = [4, 2, 1]
const C_COST = [80, 100, 140]
const C_SPEED = [100, 75, 50]
const C_RANGE = [0, 200, 0]
const C_RADIUS = [20, 25, 40]
const C_MASS = [400, 900, 2000]
const C_HP = [25, 45, 200]
const C_BUILD = [5, 8, 10]

type Body = { x: number; y: number; r: number; m: number }
type SiteStatic = { id: number; x: number; y: number; r: number; m: number; area: number }
type Site = {
  gold: number // remaining gold (-1 unknown)
  goldKnown: boolean // gold is exact (seen, or derived from the mirror site), not a default estimate
  maxMine: number // max mine size (-1 unknown)
  type: number // NONE / MINE / TOWER / BARRACKS
  owner: number // -1, 0, 1 (referee index)
  rate: number // mine income rate
  hp: number // tower health
  range: number // tower attack radius
  ctype: number // barracks creep type
  progress: number // barracks progress
  training: boolean
}
type Creep = { x: number; y: number; r: number; m: number; owner: number; type: number; hp: number }
type Queen = { x: number; y: number; r: number; m: number }
type State = {
  turn: number // turns played so far (0 on the first turn): same-site build tie-break, see step()
  map: SiteStatic[] // shared between clones
  sites: Site[]
  creeps: [Creep[], Creep[]] // per player, in spawn order (referee activeCreeps)
  queens: [Queen, Queen]
  hp: [number, number] // queen health
  gold: [number, number]
}

// Queen command: WAIT, MOVE x y, BUILD site kind. build: 0 MINE, 1 TOWER, 2 BARRACKS-KNIGHT, 3 BARRACKS-ARCHER, 4 BARRACKS-GIANT
const A_WAIT = 0
const A_MOVE = 1
const A_BUILD = 2
type Action = { kind: number; x: number; y: number; site: number; build: number; train: number[] }

const newAction = (): Action => ({ kind: A_WAIT, x: 0, y: 0, site: -1, build: 0, train: [] })

const BUILD_NAMES = ["MINE", "TOWER", "BARRACKS-KNIGHT", "BARRACKS-ARCHER", "BARRACKS-GIANT"]

function parseAction(queenLine: string, trainLine: string): Action {
  const a = newAction()
  const t = queenLine.trim().split(" ")
  if (t[0] === "MOVE") {
    a.kind = A_MOVE
    a.x = parseInt(t[1])
    a.y = parseInt(t[2])
  } else if (t[0] === "BUILD") {
    a.kind = A_BUILD
    a.site = parseInt(t[1])
    a.build = BUILD_NAMES.indexOf(t[2])
  }
  const u = trainLine.trim().split(" ")
  for (let i = 1; i < u.length; i++) if (u[i] !== "") a.train.push(parseInt(u[i]))
  return a
}

function formatAction(a: Action): [string, string] {
  const q =
    a.kind === A_MOVE ? `MOVE ${a.x} ${a.y}` : a.kind === A_BUILD ? `BUILD ${a.site} ${BUILD_NAMES[a.build]}` : "WAIT"
  return [q, a.train.length ? "TRAIN " + a.train.join(" ") : "TRAIN"]
}

function emptySite(): Site {
  return {
    gold: -1,
    goldKnown: false,
    maxMine: -1,
    type: NONE,
    owner: -1,
    rate: 0,
    hp: 0,
    range: 0,
    ctype: 0,
    progress: 0,
    training: false,
  }
}

function makeCreep(owner: number, type: number, x: number, y: number, hp: number): Creep {
  return { x, y, r: C_RADIUS[type], m: C_MASS[type], owner, type, hp }
}

function clone(s: State): State {
  const sites = new Array<Site>(s.sites.length)
  for (let i = 0; i < sites.length; i++) {
    const o = s.sites[i]
    sites[i] = {
      gold: o.gold,
      goldKnown: o.goldKnown,
      maxMine: o.maxMine,
      type: o.type,
      owner: o.owner,
      rate: o.rate,
      hp: o.hp,
      range: o.range,
      ctype: o.ctype,
      progress: o.progress,
      training: o.training,
    }
  }
  const cc = (l: Creep[]) => {
    const r = new Array<Creep>(l.length)
    for (let i = 0; i < l.length; i++) {
      const c = l[i]
      r[i] = { x: c.x, y: c.y, r: c.r, m: c.m, owner: c.owner, type: c.type, hp: c.hp }
    }
    return r
  }
  const q = (o: Queen): Queen => ({ x: o.x, y: o.y, r: QUEEN_R, m: QUEEN_MASS })
  return {
    turn: s.turn,
    map: s.map,
    sites,
    creeps: [cc(s.creeps[0]), cc(s.creeps[1])],
    queens: [q(s.queens[0]), q(s.queens[1])],
    hp: [s.hp[0], s.hp[1]],
    gold: [s.gold[0], s.gold[1]],
  }
}

// ---------------------------------------------------------------- vector helpers (Vector2.kt)

const EPS2 = 1e-6 * 1e-6 // Vector2.normalized: len < 1e-6, compared on squares

// o = o.towards(t, maxD)
function towards(o: { x: number; y: number }, tx: number, ty: number, maxD: number) {
  const ex = o.x - tx
  const ey = o.y - ty
  const sq = ex * ex + ey * ey
  if (sq < maxD * maxD) {
    o.x = tx
    o.y = ty
    return
  }
  const dx = tx - o.x
  const dy = ty - o.y
  const lsq = dx * dx + dy * dy
  let nx = 1
  let ny = 0
  if (!(lsq < EPS2)) {
    const l = Math.sqrt(lsq)
    nx = dx / l
    ny = dy / l
  }
  o.x = o.x + nx * maxD
  o.y = o.y + ny * maxD
}

const d2 = (ax: number, ay: number, cx: number, cy: number) => {
  const dx = ax - cx
  const dy = ay - cy
  return dx * dx + dy * dy
}

// ---------------------------------------------------------------- collisions (MapBuilding.kt)

// Bodies are copied into flat arrays for the passes (monomorphic, no allocation): units first in the
// referee's list order (p0 creeps, p0 queen, p1 creeps, p1 queen), then the sites.
let cap = 128
let bx = new Float64Array(cap)
let by = new Float64Array(cap)
let br = new Float64Array(cap)
let bm = new Float64Array(cap)
const units: Body[] = []
let nu = 0
let nb = 0

function collectBodies(s: State) {
  units.length = 0
  for (const c of s.creeps[0]) units.push(c)
  units.push(s.queens[0])
  for (const c of s.creeps[1]) units.push(c)
  units.push(s.queens[1])
  nu = units.length
  nb = nu + s.map.length
  if (nb > cap) {
    while (cap < nb) cap *= 2
    bx = new Float64Array(cap)
    by = new Float64Array(cap)
    br = new Float64Array(cap)
    bm = new Float64Array(cap)
  }
  for (let i = 0; i < nu; i++) {
    const u = units[i]
    bx[i] = u.x
    by[i] = u.y
    br[i] = u.r
    bm[i] = u.m
  }
  for (let i = nu; i < nb; i++) {
    const o = s.map[i - nu]
    bx[i] = o.x
    by[i] = o.y
    br[i] = o.r
    bm[i] = 0
  }
}

function storeBodies() {
  for (let i = 0; i < nu; i++) {
    units[i].x = bx[i]
    units[i].y = by[i]
  }
}

// One collisionCheck pass: for every body u1 in list order, clamp it inside the map, then for every
// other body u2 (list order) push both apart when they overlap. Site/site pairs are skipped: sites
// never overlap each other and never move (their clamp box is assumed to hold them).
// Returns true if something was corrected.
function collisionPass(): boolean {
  let any = false
  for (let i = 0; i < nb; i++) {
    const m1 = bm[i]
    const r1 = br[i]
    if (m1 !== 0) {
      const maxX = W - r1
      const maxY = H - r1
      if (bx[i] < r1) bx[i] = r1
      else if (bx[i] > maxX) bx[i] = maxX
      if (by[i] < r1) by[i] = r1
      else if (by[i] > maxY) by[i] = maxY
    }
    const nj = m1 === 0 ? nu : nb
    for (let j = 0; j < nj; j++) {
      if (j === i) continue
      const ex = bx[i] - bx[j]
      const ey = by[i] - by[j]
      const rs = r1 + br[j]
      const dd = ex * ex + ey * ey
      if (dd >= rs * rs) continue // sqrt(dd) >= rs: no overlap (exact shortcut, rs is an integer)
      const m2 = bm[j]
      if (m1 === 0 && m2 === 0) continue
      const overlap = rs + 0.0 - Math.sqrt(dd)
      if (overlap <= 1e-6) continue
      let k1: number
      let k2: number
      if (m1 === 0) {
        k1 = 0
        k2 = overlap + 1.0
      } else if (m2 === 0) {
        k1 = overlap + 1.0
        k2 = 0
      } else {
        k1 = (m2 / (m1 + m2)) * overlap + 1.0
        k2 = (m1 / (m1 + m2)) * overlap + 1.0
      }
      const dx = bx[j] - bx[i]
      const dy = by[j] - by[i]
      const lsq = dx * dx + dy * dy
      let nx = 1
      let ny = 0
      if (!(lsq < EPS2)) {
        const l = Math.sqrt(lsq)
        nx = dx / l
        ny = dy / l
      }
      if (m1 !== 0) {
        bx[i] = bx[i] - nx * k1
        by[i] = by[i] - ny * k1
      }
      if (m2 !== 0) {
        bx[j] = bx[j] + nx * k2
        by[j] = by[j] + ny * k2
      }
      any = true
    }
  }
  return any
}

// MapBuilding.fixCollisions: up to maxIterations passes, until one corrects nothing.
function fixCollisions(s: State, maxIterations: number) {
  collectBodies(s)
  for (let it = 0; it < maxIterations; it++) if (!collisionPass()) break
  storeBodies()
}

// ---------------------------------------------------------------- turn

const sorted: Creep[] = []
const sched = { n: 0, p: [0, 0], site: [0, 0], build: [0, 0] }

function nearestEnemyCreep(s: State, c: Creep): Creep | null {
  const l = s.creeps[1 - c.owner]
  let best: Creep | null = null
  let bd = Infinity
  for (let i = 0; i < l.length; i++) {
    const e = l[i]
    const d = d2(e.x, e.y, c.x, c.y)
    if (d < bd) {
      bd = d
      best = e
    }
  }
  return best
}

function closestSite(s: State, x: number, y: number): number {
  let best = -1
  let bd = Infinity
  const map = s.map
  for (let i = 0; i < map.length; i++) {
    const d = d2(map[i].x, map[i].y, x, y)
    if (d < bd) {
      bd = d
      best = i
    }
  }
  return best
}

function damageCreep(c: Creep, amount: number) {
  if (amount <= 0) return
  c.hp -= amount
  if (c.hp < 0) c.hp = 0
}

function damageQueen(s: State, p: number, amount: number) {
  if (amount <= 0) return
  s.hp[p] -= amount
  if (s.hp[p] < 0) s.hp[p] = 0
}

function processPlayerActions(s: State, actions: [Action, Action]) {
  sched.n = 0
  for (let p = 0; p < 2; p++) {
    const a = actions[p]
    // TRAIN
    const tr = a.train
    if (tr.length > 0) {
      let ok = true
      let sum = 0
      for (let i = 0; i < tr.length && ok; i++) {
        const id = tr[i]
        const st = id >= 0 && id < s.sites.length ? s.sites[id] : null
        if (!st || st.type !== BARRACKS || st.owner !== p || st.training) ok = false
        else {
          for (let j = 0; j < i; j++) if (tr[j] === id) ok = false
          sum += C_COST[st.ctype]
        }
      }
      if (ok && sum <= s.gold[p]) {
        s.gold[p] -= sum
        for (let i = 0; i < tr.length; i++) {
          const st = s.sites[tr[i]]
          st.progress = 0
          st.training = true
        }
      }
    }
    // Queen command
    const q = s.queens[p]
    if (a.kind === A_MOVE) towards(q, a.x, a.y, QUEEN_SPEED)
    else if (a.kind === A_BUILD) {
      // An unknown site or structure makes the referee deactivate the player: treated as WAIT here.
      if (!(a.site >= 0 && a.site < s.map.length && a.build >= 0 && a.build < 5)) continue
      const o = s.map[a.site]
      const lim = QUEEN_R + o.r + TOUCH
      if (d2(o.x, o.y, q.x, q.y) < lim * lim) {
        const st = s.sites[a.site]
        if (st.type !== NONE && st.owner === 1 - p) continue
        if (st.type === BARRACKS && st.owner === p && st.training) continue
        const k = sched.n++
        sched.p[k] = p
        sched.site[k] = a.site
        sched.build[k] = a.build
      } else towards(q, o.x, o.y, QUEEN_SPEED)
    }
  }
  let from = 0
  let to = sched.n
  if (sched.n === 2 && sched.site[0] === sched.site[1]) {
    if (s.turn % 2 === 0) from = 1
    else to = 1
  }
  for (let k = from; k < to; k++) {
    const p = sched.p[k]
    const st = s.sites[sched.site[k]]
    const b = sched.build[k]
    if (b === 0) {
      if (st.type === MINE) {
        st.rate++
        if (st.rate > st.maxMine) st.rate = st.maxMine
      } else {
        st.type = MINE
        st.owner = p
        st.rate = 1
        st.training = false
      }
    } else if (b === 1) {
      if (st.type === TOWER) {
        st.hp += TOWER_HP_INCREMENT
        if (st.hp > TOWER_HP_MAXIMUM) st.hp = TOWER_HP_MAXIMUM
      } else {
        st.type = TOWER
        st.owner = p
        st.hp = TOWER_HP_INITIAL
        st.range = 0
        st.training = false
      }
    } else {
      st.type = BARRACKS
      st.owner = p
      st.ctype = b - 2
      st.progress = 0
      st.training = false
    }
  }
}

function moveCreep(s: State, c: Creep, frames: number) {
  const speed = C_SPEED[c.type] * frames
  if (c.type === KNIGHT) {
    const eq = s.queens[1 - c.owner]
    const lim = c.r + QUEEN_R + C_RANGE[KNIGHT]
    if (d2(c.x, c.y, eq.x, eq.y) > lim * lim) moveToward3(c, eq.x, eq.y, speed)
  } else if (c.type === ARCHER) {
    const e = nearestEnemyCreep(s, c)
    const tx = e ? e.x : s.queens[c.owner].x
    const ty = e ? e.y : s.queens[c.owner].y
    const lim = c.r + (e ? e.r : QUEEN_R) + C_RANGE[ARCHER]
    if (d2(c.x, c.y, tx, ty) > lim * lim) moveToward3(c, tx, ty, speed)
  } else {
    const map = s.map
    const sites = s.sites
    const enemy = 1 - c.owner
    let best = -1
    let bd = Infinity
    for (let i = 0; i < map.length; i++) {
      const st = sites[i]
      if (st.type !== TOWER || st.owner !== enemy) continue
      const d = d2(map[i].x, map[i].y, c.x, c.y)
      if (d < bd) {
        bd = d
        best = i
      }
    }
    if (best >= 0) towards(c, map[best].x, map[best].y, speed)
  }
}

// location = location.towards(target + (location - target).resizedTo(3.0), speed)
function moveToward3(c: Creep, tx: number, ty: number, speed: number) {
  const vx = c.x - tx
  const vy = c.y - ty
  const lsq = vx * vx + vy * vy
  let nx = 1
  let ny = 0
  if (!(lsq < EPS2)) {
    const l = Math.sqrt(lsq)
    nx = vx / l
    ny = vy / l
  }
  towards(c, tx + nx * 3.0, ty + ny * 3.0, speed)
}

function dealDamage(s: State, c: Creep) {
  if (c.type === KNIGHT) {
    const eq = s.queens[1 - c.owner]
    const lim = c.r + QUEEN_R + C_RANGE[KNIGHT] + TOUCH
    if (d2(c.x, c.y, eq.x, eq.y) < lim * lim) {
      s.hp[1 - c.owner] -= 1
      if (s.hp[1 - c.owner] < 0) s.hp[1 - c.owner] = 0
    }
  } else if (c.type === ARCHER) {
    const e = nearestEnemyCreep(s, c)
    if (!e) return
    const lim = c.r + e.r + C_RANGE[ARCHER] + TOUCH
    if (d2(c.x, c.y, e.x, e.y) < lim * lim) damageCreep(e, e.type === GIANT ? 10 : 2)
  } else {
    const map = s.map
    const enemy = 1 - c.owner
    for (let i = 0; i < map.length; i++) {
      const st = s.sites[i]
      if (st.type !== TOWER || st.owner !== enemy) continue
      const lim = c.r + map[i].r + TOUCH
      if (d2(map[i].x, map[i].y, c.x, c.y) < lim * lim) {
        st.hp -= GIANT_BUST_RATE
        break
      }
    }
  }
}

function processCreeps(s: State) {
  sorted.length = 0
  for (let t = 0; t < 3; t++)
    for (let p = 0; p < 2; p++) {
      const l = s.creeps[p]
      for (let i = 0; i < l.length; i++) if (l[i].type === t) sorted.push(l[i])
    }
  const frames = 1.0 / 5
  for (let rep = 0; rep < 5; rep++) {
    for (let i = 0; i < sorted.length; i++) moveCreep(s, sorted[i], frames)
    fixCollisions(s, 1)
  }
  for (let i = 0; i < sorted.length; i++) dealDamage(s, sorted[i])

  // Tear down enemy mines
  for (let i = 0; i < sorted.length; i++) {
    const c = sorted[i]
    const k = closestSite(s, c.x, c.y)
    const o = s.map[k]
    const lim = o.r + c.r + TOUCH
    if (d2(o.x, o.y, c.x, c.y) >= lim * lim) continue
    const st = s.sites[k]
    if (st.type === MINE && st.owner !== c.owner) clearSite(st)
  }
  for (let i = 0; i < sorted.length; i++) damageCreep(sorted[i], 1)

  // Queens tear down enemy mines and barracks
  for (let p = 0; p < 2; p++) {
    const q = s.queens[p]
    const k = closestSite(s, q.x, q.y)
    const o = s.map[k]
    const lim = o.r + QUEEN_R + TOUCH
    if (d2(o.x, o.y, q.x, q.y) >= lim * lim) continue
    const st = s.sites[k]
    if ((st.type === MINE || st.type === BARRACKS) && st.owner !== p) clearSite(st)
  }
}

function clearSite(st: Site) {
  st.type = NONE
  st.owner = -1
  st.training = false
}

function actTower(s: State, st: Site, o: SiteStatic) {
  const enemy = 1 - st.owner
  const l = s.creeps[enemy]
  let best: Creep | null = null
  let bd = Infinity
  for (let j = 0; j < l.length; j++) {
    const d = d2(l[j].x, l[j].y, o.x, o.y)
    if (d < bd) {
      bd = d
      best = l[j]
    }
  }
  const rr = st.range * st.range
  if (best !== null && bd < rr) {
    const shot = Math.sqrt(bd)
    damageCreep(best, 3 + Math.trunc((st.range - shot) / 200))
  } else {
    const q = s.queens[enemy]
    const qd = d2(q.x, q.y, o.x, o.y)
    if (qd < rr) {
      const shot = Math.sqrt(qd)
      damageQueen(s, enemy, 1 + Math.trunc((st.range - shot) / 200))
    }
  }
  st.hp -= 4
  const rad = Math.sqrt((st.hp * 1000 + o.area) / Math.PI)
  st.range = rad === rad ? Math.trunc(rad) : 0
  if (st.hp <= 0) clearSite(st)
}

function actMine(s: State, st: Site) {
  const cash = Math.min(st.rate, st.gold)
  s.gold[st.owner] += cash
  st.gold -= cash
  if (st.gold < 0) st.gold = 0
  if (st.gold <= 0) clearSite(st)
}

function actBarracks(s: State, st: Site, o: SiteStatic) {
  if (st.training) {
    st.progress++
    if (st.progress === C_BUILD[st.ctype]) {
      st.progress = 0
      st.training = false
      spawn(s, st, o)
    }
  }
}

function removeDead(s: State) {
  for (let p = 0; p < 2; p++) {
    const l = s.creeps[p]
    let k = 0
    for (let i = 0; i < l.length; i++) if (l[i].hp !== 0) l[k++] = l[i]
    l.length = k
  }
}

function actSites(s: State) {
  const map = s.map
  const n = map.length
  for (let i = 0; i < n; i++) if (s.sites[i].type === TOWER) actTower(s, s.sites[i], map[i])
  removeDead(s)
  for (let i = 0; i < n; i++) if (s.sites[i].type === BARRACKS) actBarracks(s, s.sites[i], map[i])
  for (let i = 0; i < n; i++) if (s.sites[i].type === MINE) actMine(s, s.sites[i])
}

const SPAWN_DX = [1, -1, 1, -1]
const SPAWN_DY = [-1, 1, 1, -1]

function spawn(s: State, st: Site, o: SiteStatic) {
  const p = st.owner
  const t = st.ctype
  const eq = s.queens[1 - p]
  for (let iter = 0; iter < C_COUNT[t]; iter++) {
    const cr = makeCreep(p, t, o.x + SPAWN_DX[iter], o.y + SPAWN_DY[iter], C_HP[t])
    towards(cr, eq.x, eq.y, 30.0)
    s.creeps[p].push(cr)
  }
  fixCollisions(s, 999)
}

// Applies one full turn (Referee.gameTurn after sendGameStates): per player (0 then 1) TRAIN then
// the queen command; scheduled builds; creeps move 5 x 1/5 with one collision pass each, attack,
// raze enemy mines, age; queens raze enemy mines/barracks; structures act; dead creeps removed;
// positions rounded. Same-site builds: the referee drops scheduledBuildings[turn % 2], so on even
// turns (the first turn is turn 0 per the statement) the second player builds; not yet seen in a
// replay. Mutates `s` (clone first to keep it) and increments s.turn.
function step(s: State, actions: [Action, Action]) {
  processPlayerActions(s, actions)
  processCreeps(s)
  actSites(s)
  removeDead(s)
  for (let p = 0; p < 2; p++) {
    for (const c of s.creeps[p]) {
      c.x = Math.round(c.x)
      c.y = Math.round(c.y)
    }
    const q = s.queens[p]
    q.x = Math.round(q.x)
    q.y = Math.round(q.y)
  }
  s.turn++
}

const gameOver = (s: State) => s.hp[0] === 0 || s.hp[1] === 0

// ---------------------------------------------------------------- input <-> state

function parseInit(lines: string[]): SiteStatic[] {
  const n = parseInt(lines[0])
  const map: SiteStatic[] = []
  for (let i = 1; i <= n; i++) {
    const [id, x, y, r] = lines[i].split(" ").map(Number)
    map[id] = { id, x, y, r, m: 0, area: Math.PI * r * r }
  }
  return map
}

// Map generation bonus: +1 max mine size and +50 gold within 500 of the centre, again within 200.
function centreBonus(o: SiteStatic) {
  const d = d2(o.x, o.y, W / 2, H / 2)
  return (d < 500 * 500 ? 1 : 0) + (d < 200 * 200 ? 1 : 0)
}

// Our side from our first-turn queen position: the first player spawns top-left.
const sideFromQueen = (x: number) => (x < W / 2 ? 0 : 1)

// Builds a State from one turn's input lines (gold/touched, one line per site, unit count, units).
// `me` is our referee index. Info hidden from us (enemy gold, hidden site gold / max mine size / mine rate)
// is taken from the pair site when visible (2k <-> 2k+1 are mirrors with the same initial values),
// from `prev` when given (e.g. the state we simulated from last turn), else from upper-bound
// defaults (max mine 3 + centre bonus, gold 250 + 50 per bonus). `turn` = turns played so far.
function stateFromInput(
  map: SiteStatic[],
  lines: string[],
  me: number,
  turn: number,
  prev?: State | null
): State {
  const en = 1 - me
  const n = map.length
  let li = 0
  const [gold] = lines[li++].split(" ").map(Number)
  const sites: Site[] = []
  for (let i = 0; i < n; i++) {
    const [id, g, mx, type, owner, p1, p2] = lines[li++].split(" ").map(Number)
    const st = emptySite()
    st.gold = g
    st.goldKnown = g >= 0
    st.maxMine = mx
    st.type = type
    st.owner = owner < 0 ? -1 : owner === 0 ? me : en
    if (type === MINE) st.rate = p1
    else if (type === TOWER) {
      st.hp = p1
      st.range = p2
    } else if (type === BARRACKS) {
      st.ctype = p2
      st.training = p1 > 0
      st.progress = p1 > 0 ? C_BUILD[p2] - p1 : 0
    }
    sites[id] = st
  }
  for (let i = 0; i < n; i++) {
    const st = sites[i]
    const pv = prev ? prev.sites[i] : null
    const pair = sites[i ^ 1]
    if (st.maxMine < 0)
      st.maxMine = pair.maxMine >= 0 ? pair.maxMine : pv && pv.maxMine >= 0 ? pv.maxMine : 3 + centreBonus(map[i])
    if (st.gold < 0) {
      // Unknown initial gold is estimated as 250 + 50 per bonus; once the mirror site is seen
      // unbuilt, its gold is the initial value and whatever the estimate lost since is subtracted.
      const guess = 250 + 50 * centreBonus(map[i])
      if (pv && pv.goldKnown) {
        st.gold = pv.gold
        st.goldKnown = true
      } else if (pair.goldKnown && pair.type === NONE) {
        st.gold = Math.max(0, pair.gold - (guess - (pv ? pv.gold : guess)))
        st.goldKnown = true
      } else st.gold = pv ? pv.gold : guess
    }
    if (st.type === MINE && st.rate < 0) {
      st.rate = pv && pv.type === MINE && pv.owner === st.owner ? pv.rate : 1
      if (st.rate > st.maxMine) st.rate = st.maxMine
    }
  }
  const nu = parseInt(lines[li++])
  const creeps: [Creep[], Creep[]] = [[], []]
  const queens: [Queen, Queen] = [
    { x: 0, y: 0, r: QUEEN_R, m: QUEEN_MASS },
    { x: 0, y: 0, r: QUEEN_R, m: QUEEN_MASS },
  ]
  const hp: [number, number] = [0, 0]
  for (let i = 0; i < nu; i++) {
    const [x, y, owner, type, h] = lines[li++].split(" ").map(Number)
    const p = owner === 0 ? me : en
    if (type < 0) {
      queens[p].x = x
      queens[p].y = y
      hp[p] = h
    } else creeps[p].push(makeCreep(p, type, x, y, h))
  }
  const g: [number, number] = [0, 0]
  g[me] = gold
  g[en] = prev ? prev.gold[en] : 100
  return { turn, map, sites, creeps, queens, hp, gold: g }
}

// Renders the turn input that player `me` would receive for state `s` (Referee.sendGameStates).
function renderInput(s: State, me: number): string[] {
  const out: string[] = []
  const q = s.queens[me]
  let touched = -1
  let count = 0
  for (const o of s.map) {
    const lim = o.r + QUEEN_R + TOUCH
    if (d2(o.x, o.y, q.x, q.y) < lim * lim) {
      touched = o.id
      count++
    }
  }
  out.push(`${s.gold[me]} ${count === 1 ? touched : -1}`)
  const own = (p: number) => (p < 0 ? -1 : p === me ? 0 : 1)
  for (let i = 0; i < s.map.length; i++) {
    const o = s.map[i]
    const st = s.sites[i]
    const vis = (st.type !== NONE && st.owner === me) || d2(o.x, o.y, q.x, q.y) < VISION * VISION
    let tail = "-1 -1 -1 -1"
    if (st.type === MINE) tail = `0 ${own(st.owner)} ${vis ? st.rate : -1} -1`
    else if (st.type === TOWER) tail = `1 ${own(st.owner)} ${st.hp} ${st.range}`
    else if (st.type === BARRACKS)
      tail = `2 ${own(st.owner)} ${st.training ? C_BUILD[st.ctype] - st.progress : 0} ${st.ctype}`
    out.push(`${o.id} ${vis ? st.gold : -1} ${vis ? st.maxMine : -1} ${tail}`)
  }
  out.push(`${s.creeps[0].length + s.creeps[1].length + 2}`)
  for (let p = 0; p < 2; p++) {
    for (const c of s.creeps[p]) out.push(`${c.x} ${c.y} ${own(p)} ${c.type} ${c.hp}`)
    out.push(`${s.queens[p].x} ${s.queens[p].y} ${own(p)} -1 ${s.hp[p]}`)
  }
  return out
}

// Planner bot for Code Royale on the exact engine (engine.ts, checked 160/160
// turns on a replay). Bundled into ../code-royale.ts by build.mjs.
//
// After the contest winner's postmortem (RoboStac): the queen's actions come
// from a beam search over 8 compass moves and the builds possible on the
// touched site, played on the engine with the enemy queen idle (repairing a
// tower it touches) and no training; the evaluation weighs our queen HP far
// above anything else, then the enemy HP, income, towers, knight barracks and
// enemy buildings, plus Agade's knight-threat term. Training is a separate
// rule set (early knights, 8-knight bursts, spend at the end).
const init = [readline()]
for (let i = 0, n = parseInt(init[0]); i < n; i++) init.push(readline())
const map = parseInit(init)
const numSites = map.length

let me = -1
let prev: State | null = null
let turn = 0

const dist = (ax: number, ay: number, bx: number, by: number) => Math.sqrt((ax - bx) * (ax - bx) + (ay - by) * (ay - by))

function touched(s: State, p: number): number {
  const q = s.queens[p]
  let found = -1
  let count = 0
  for (const o of map) {
    const lim = o.r + QUEEN_R + TOUCH
    if ((o.x - q.x) * (o.x - q.x) + (o.y - q.y) * (o.y - q.y) < lim * lim) {
      found = o.id
      count++
    }
  }
  return count === 1 ? found : -1
}

const underEnemyTower = (s: State, x: number, y: number, en: number) => {
  for (let i = 0; i < numSites; i++) {
    const st = s.sites[i]
    if (st.type === TOWER && st.owner === en && dist(x, y, map[i].x, map[i].y) < st.range) return true
  }
  return false
}

function evaluate(s: State): number {
  const en = 1 - me
  let v = 100 * s.hp[me] - 10 * s.hp[en]
  if (s.hp[me] <= 0) v -= 100000
  let income = 0
  let towers = 0
  let mines = 0
  let kb = 0
  let kbDist = Infinity
  const eq = s.queens[en]
  for (let i = 0; i < numSites; i++) {
    const st = s.sites[i]
    if (st.owner === me) {
      if (st.type === MINE) {
        income += st.rate
        mines++
      } else if (st.type === TOWER) {
        towers++
        v += (towers <= 6 ? 50 : 10) + (40 * st.hp) / 800
      } else if (st.type === BARRACKS && st.ctype === KNIGHT) {
        kb++
        kbDist = Math.min(kbDist, dist(map[i].x, map[i].y, eq.x, eq.y))
      }
    } else if (st.owner === en) v -= st.type === TOWER ? 10 : 25
  }
  v += 60 * income
  if (kb === 0) v -= 400
  else if (kb === 2) v += 100
  else if (kb > 2) v -= 300
  // Tower turtles (the boss raises 11-17): a giant barracks to bust them.
  let enemyTowers = 0
  let gb = 0
  for (const st of s.sites) {
    if (st.owner === en && st.type === TOWER) enemyTowers++
    if (st.owner === me && st.type === BARRACKS && st.ctype === GIANT) gb++
  }
  if (enemyTowers >= 5) v += gb === 1 ? 150 : gb === 0 ? -100 : -300
  if (kbDist < Infinity) v -= 0.03 * kbDist
  if (towers < 5 && mines > 2 && towers < mines) v -= 150
  // Agade's knight threat: HP over distance, a knight far enough dies first.
  const q = s.queens[me]
  for (const k of s.creeps[en]) {
    if (k.type !== KNIGHT) continue
    const d = Math.max(1, dist(k.x, k.y, q.x, q.y))
    v -= 1000 * Math.max(0, k.hp / d - 0.02)
  }
  // Keep expanding: distance to the nearest free site out of enemy tower range.
  let near = Infinity
  for (let i = 0; i < numSites; i++) {
    const st = s.sites[i]
    if (st.type !== NONE) continue
    const d = dist(q.x, q.y, map[i].x, map[i].y)
    if (d < near && !underEnemyTower(s, map[i].x, map[i].y, en)) near = d
  }
  if (near < Infinity) v -= 0.2 * near
  // Arena losses: queens cornered against walls / in corners.
  const edge = Math.min(q.x, q.y, 1920 - q.x, 1000 - q.y)
  if (edge < 200) v -= 2 * (200 - edge)
  const corner = Math.min(
    Math.hypot(q.x, q.y),
    Math.hypot(1920 - q.x, q.y),
    Math.hypot(q.x, 1000 - q.y),
    Math.hypot(1920 - q.x, 1000 - q.y),
  )
  if (corner < 400) v -= 2 * (400 - corner)
  return v
}

// Candidate queen actions from a state.
function options(s: State): Action[] {
  const out: Action[] = []
  const q = s.queens[me]
  for (let k = 0; k < 8; k++) {
    const a = newAction()
    a.kind = A_MOVE
    a.x = Math.round(Math.max(0, Math.min(1920, q.x + Math.cos((k * Math.PI) / 4) * 100)))
    a.y = Math.round(Math.max(0, Math.min(1000, q.y + Math.sin((k * Math.PI) / 4) * 100)))
    out.push(a)
  }
  const t = touched(s, me)
  if (t >= 0) {
    const st = s.sites[t]
    const build = (b: number) => {
      const a = newAction()
      a.kind = A_BUILD
      a.site = t
      a.build = b
      out.push(a)
    }
    let kb = 0
    for (const o of s.sites) if (o.owner === me && o.type === BARRACKS && o.ctype === KNIGHT) kb++
    let gb = 0
    let et = 0
    for (const o of s.sites) {
      if (o.owner === me && o.type === BARRACKS && o.ctype === GIANT) gb++
      if (o.owner === 1 - me && o.type === TOWER) et++
    }
    if (st.type === NONE) {
      if (st.gold > 0) build(0)
      build(1)
      if (kb < 2) build(2)
      if (gb === 0 && et >= 5) build(4)
    } else if (st.owner === me) {
      if (st.type === MINE && st.rate < st.maxMine && st.gold > 0) build(0)
      if (st.type === TOWER && st.hp < 700) build(1)
    }
  }
  return out
}

function enemyAction(s: State): Action {
  const en = 1 - me
  const a = newAction()
  const t = touched(s, en)
  if (t >= 0 && s.sites[t].type === TOWER && s.sites[t].owner === en) {
    a.kind = A_BUILD
    a.site = t
    a.build = 1
  }
  return a
}

type Node = { s: State; first: Action; score: number }

function plan(root: State, deadline: number): Action {
  const WIDTH = 8
  let beam: Node[] = [{ s: root, first: newAction(), score: 0 }]
  let best: Node | null = null
  for (let depth = 0; depth < 12; depth++) {
    const next: Node[] = []
    for (const n of beam) {
      for (const a of options(n.s)) {
        if (Date.now() > deadline) break
        const c = clone(n.s)
        const acts: [Action, Action] = [newAction(), newAction()]
        acts[me] = a
        acts[1 - me] = enemyAction(c)
        step(c, acts)
        // Score: accumulated evals (early turns count, the last most).
        const sc = n.score * 0.7 + evaluate(c)
        next.push({ s: c, first: depth === 0 ? a : n.first, score: sc })
      }
    }
    if (!next.length) break
    next.sort((x, y) => y.score - x.score)
    beam = next.slice(0, WIDTH)
    best = beam[0]
    if (Date.now() > deadline) break
  }
  return best ? best.first : newAction()
}

// Spend everything, as the boss does (30-45 trainings a game against our
// 8-10 with bursts): a giant first when the enemy turtles behind 5+ towers
// and none of ours is alive, then knights from the barracks closest to the
// enemy queen.
function training(s: State): number[] {
  const en = 1 - me
  const eq = s.queens[en]
  const ready: number[] = []
  let giantB = -1
  let enemyTowers = 0
  for (let i = 0; i < numSites; i++) {
    const st = s.sites[i]
    if (st.owner === en && st.type === TOWER) enemyTowers++
    if (st.owner !== me || st.type !== BARRACKS || st.training) continue
    if (st.ctype === KNIGHT) ready.push(i)
    else if (st.ctype === GIANT) giantB = i
  }
  ready.sort((a, b) => dist(map[a].x, map[a].y, eq.x, eq.y) - dist(map[b].x, map[b].y, eq.x, eq.y))
  let g = s.gold[me]
  const out: number[] = []
  const giantAlive = s.creeps[me].some(c => c.type === GIANT)
  if (giantB >= 0 && enemyTowers >= 5 && !giantAlive) {
    if (g < C_COST[GIANT]) return out // save for it
    out.push(giantB)
    g -= C_COST[GIANT]
  }
  for (const i of ready)
    if (g >= C_COST[KNIGHT]) {
      out.push(i)
      g -= C_COST[KNIGHT]
    }
  return out
}

while (true) {
  const lines: string[] = [readline()]
  for (let i = 0; i < numSites; i++) lines.push(readline())
  const nu = readline()
  lines.push(nu)
  for (let i = 0, n = parseInt(nu); i < n; i++) lines.push(readline())
  const start = Date.now()
  if (me < 0) {
    for (let i = numSites + 2; i < lines.length; i++) {
      const [x, , owner, type] = lines[i].split(" ").map(Number)
      if (owner === 0 && type === -1) me = sideFromQueen(x)
    }
  }
  const s = stateFromInput(map, lines, me, turn, prev)
  const a = plan(s, start + (turn === 0 ? 300 : 32))
  a.train = training(s)
  const out = formatAction(a)
  // Keep the simulated next state for hidden info (enemy gold, unseen sites).
  const acts: [Action, Action] = [newAction(), newAction()]
  acts[me] = a
  acts[1 - me] = enemyAction(s)
  prev = clone(s)
  step(prev, acts)
  turn++
  console.log(out[0])
  console.log(out[1])
}

void [OBSTACLE_GAP, parseAction, gameOver, renderInput]
