// 🎮 CodinGame Multiplayer - spring-challenge-2026-troll-farm
// https://www.codingame.com/multiplayer/bot-programming/spring-challenge-2026-troll-farm
// Generated by troll-farm-tools/build.mjs (engine.ts + bot.ts + main.ts): edit those files.
// Port of the Troll Farm referee (github.com/eulerscheZahl/Troll-Farm, level 4 rules): map
// generation (same procedure, own RNG), task parsing / validation, the per-priority resolution
// (MOVE, HARVEST, PLANT, CHOP, PICK, TRAIN, DROP, MINE), plant growth and the end conditions.
// Cells are indexed c = y * W + x. Players are 0 / 1 (absolute seats).

const PLUM = 0
const LEMON = 1
const APPLE = 2
const BANANA = 3
const IRON = 4
const WOOD = 5
const ITEMS = ["PLUM", "LEMON", "APPLE", "BANANA", "IRON", "WOOD"]
const COOLDOWN = [8, 8, 9, 6]
const WATER_BOOST = [5, 5, 7, 2]
const FINAL_HEALTH = [12, 12, 20, 6]
const DELTA_HEALTH = [2, 2, 3, 1]
const MAX_SIZE = 4
const MAX_FRUITS = 3
const GAME_TURNS = 300

const GRASS = 0
const WATER = 1
const ROCK = 2
const IRONCELL = 3
const SHACK = 4

interface Tree {
  type: number
  cell: number
  size: number
  health: number
  fruits: number
  cooldown: number
  growth: number // growth cooldown (water aware)
}
interface Troll {
  id: number
  owner: number
  cell: number
  speed: number
  carry: number
  harvest: number
  chop: number
  inv: number[] // 6 items
}
interface Game {
  W: number
  H: number
  grid: Uint8Array
  shack: number[] // per player
  inv: number[][] // per player, 6 items
  trees: Tree[]
  trolls: Troll[]
  nextId: number
  turn: number // turns played
  turnsUntilEnd: number
  over: boolean
  dead: boolean[] // killed (invalid command / timeout)
  dist?: (Int16Array | undefined)[] // BFS cache per source cell (the terrain never changes)
}

/** Cached BFS distances from one cell. */
function distFrom(g: Game, c: number): Int16Array {
  if (!g.dist) g.dist = []
  let d = g.dist[c]
  if (!d) d = g.dist[c] = bfs(g, [c])
  return d
}

class Rng {
  s: number
  constructor(seed: number) {
    this.s = seed >>> 0 || 1
  }
  next(): number {
    // mulberry32
    let t = (this.s = (this.s + 0x6d2b79f5) >>> 0)
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
  int(n: number): number {
    return Math.floor(this.next() * n)
  }
}

const sum = (a: number[]) => a[0] + a[1] + a[2] + a[3] + a[4] + a[5]

function neighbors(g: { W: number; H: number }, c: number): number[] {
  const x = c % g.W
  const y = (c - x) / g.W
  const r: number[] = []
  // Cell.java order: dx {0,1,0,-1}, dy {1,0,-1,0}
  if (y + 1 < g.H) r.push(c + g.W)
  if (x + 1 < g.W) r.push(c + 1)
  if (y - 1 >= 0) r.push(c - g.W)
  if (x - 1 >= 0) r.push(c - 1)
  return r
}

function nearType(g: Game, c: number, t: number): boolean {
  for (const n of neighbors(g, c)) if (g.grid[n] === t) return true
  return false
}

function growthCooldown(g: Game, type: number, cell: number): number {
  return COOLDOWN[type] - (nearType(g, cell, WATER) ? WATER_BOOST[type] : 0)
}

function newTree(g: Game, type: number, cell: number): Tree {
  return {
    type,
    cell,
    size: 0,
    health: FINAL_HEALTH[type] - DELTA_HEALTH[type] * MAX_SIZE,
    fruits: 0,
    cooldown: 0,
    growth: growthCooldown(g, type, cell),
  }
}

function tickTree(t: Tree) {
  if (t.cooldown > 0) t.cooldown--
  if (t.cooldown === 0 && t.health > 0) {
    if (t.size < MAX_SIZE) {
      t.size++
      t.health += DELTA_HEALTH[t.type]
      t.cooldown = t.growth
    } else if (t.fruits < MAX_FRUITS) {
      t.fruits++
      t.cooldown = t.growth
    }
  }
}

/** BFS over grass from the given sources (sources themselves get 0 whatever their type). */
function bfs(g: { W: number; H: number; grid: Uint8Array }, sources: number[]): Int16Array {
  const d = new Int16Array(g.W * g.H).fill(-1)
  const q = new Int16Array(g.W * g.H)
  let qt = 0
  for (const s of sources) {
    if (d[s] < 0) {
      d[s] = 0
      q[qt++] = s
    }
  }
  for (let qh = 0; qh < qt; qh++) {
    const c = q[qh]
    const x = c % g.W
    const nd = d[c] + 1
    if (c + g.W < g.W * g.H && d[c + g.W] < 0 && g.grid[c + g.W] === GRASS) (d[c + g.W] = nd), (q[qt++] = c + g.W)
    if (x + 1 < g.W && d[c + 1] < 0 && g.grid[c + 1] === GRASS) (d[c + 1] = nd), (q[qt++] = c + 1)
    if (c - g.W >= 0 && d[c - g.W] < 0 && g.grid[c - g.W] === GRASS) (d[c - g.W] = nd), (q[qt++] = c - g.W)
    if (x > 0 && d[c - 1] < 0 && g.grid[c - 1] === GRASS) (d[c - 1] = nd), (q[qt++] = c - 1)
  }
  return d
}

const manhattan = (W: number, a: number, b: number) =>
  Math.abs((a % W) - (b % W)) + Math.abs(Math.floor(a / W) - Math.floor(b / W))

/** Board.getNextCell: returns every equally good cell (the referee picks one at random). */
function nextCells(g: Game, cur: number, target: number, speed: number): number[] {
  const src = distFrom(g, cur)
  if (src[target] >= 0 && src[target] <= speed) return [target]
  let td: Int16Array
  if (src[target] < 0) {
    let best = 1e9
    let closest: number[] = []
    for (let c = 0; c < g.W * g.H; c++) {
      if (src[c] < 0) continue
      const d = manhattan(g.W, c, target)
      if (d < best) (best = d), (closest = [])
      if (d === best) closest.push(c)
    }
    td = bfs(g, closest)
  } else td = distFrom(g, target)
  let best = 1e9
  let res: number[] = []
  for (let c = 0; c < g.W * g.H; c++) {
    if (src[c] > speed || src[c] < 0) continue
    const d = td[c]
    if (d >= 0 && d < best) (best = d), (res = [])
    if (d === best) res.push(c)
  }
  return res
}

function trainCost(nUnits: number, talents: number[]): number[] {
  // PLUM, LEMON, APPLE, BANANA(0), IRON
  return [
    nUnits + talents[0] * talents[0],
    nUnits + talents[1] * talents[1],
    nUnits + talents[2] * talents[2],
    0,
    nUnits + talents[3] * talents[3],
    0,
  ]
}

function score(g: Game, p: number): number {
  if (g.dead[p]) return -2
  const v = g.inv[p]
  return v[0] + v[1] + v[2] + v[3] + 4 * v[5]
}

// ---------------------------------------------------------------- map generation

function createGame(seed: number): Game {
  const rng = new Rng(seed)
  for (;;) {
    const H = 8 + rng.int(4)
    const W = 2 * H
    const g: Game = {
      W,
      H,
      grid: new Uint8Array(W * H),
      shack: [0, 0],
      inv: [
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
      ],
      trees: [],
      trolls: [],
      nextId: 0,
      turn: 0,
      turnsUntilEnd: 0,
      over: false,
      dead: [false, false],
    }
    const mirror = (c: number) => W * H - 1 - c
    const treeAt = new Int16Array(W * H).fill(-1)
    const randomCell = () => {
      for (;;) {
        const c = rng.int(H) * W + rng.int(W)
        if (g.grid[c] === GRASS && treeAt[c] < 0) return c
      }
    }
    const set = (c: number, t: number) => {
      g.grid[c] = t
      g.grid[mirror(c)] = t
    }
    const nearEdge = (c: number) => neighbors(g, c).length < 4
    // rivers
    let maxTotalRiver = W * H - Math.trunc((2 * (10 + 4 * 4 + 2 + 1) * 4) / 5)
    const rivers = 2 + rng.int(2)
    for (let i = 0; i < rivers; i++) {
      let river: number | null = randomCell()
      for (let j = 0; j < 10 && nearEdge(river); j++) river = randomCell()
      while (river !== null && maxTotalRiver > 0) {
        set(river, WATER)
        const dir = rng.int(4)
        const x: number = river % W
        const y: number = (river - x) / W
        const nx = x + [0, 1, 0, -1][dir]
        const ny = y + [1, 0, -1, 0][dir]
        river = nx < 0 || ny < 0 || nx >= W || ny >= H ? null : ny * W + nx
        maxTotalRiver -= 2
      }
    }
    const inv = [0, 1, 2, 3, 4].map(() => 2 + rng.int(9))
    let shack = rng.int(H) * W + rng.int(W / 2)
    while (g.grid[shack] === WATER) shack = rng.int(H) * W + rng.int(W / 2)
    set(shack, SHACK)
    g.shack = [shack, mirror(shack)]
    for (let p = 0; p < 2; p++) {
      g.inv[p] = [...inv, 0]
      g.trolls.push({ id: g.nextId++, owner: p, cell: g.shack[p], speed: 1, carry: 1, harvest: 1, chop: 1, inv: [0, 0, 0, 0, 0, 0] })
    }
    // Unit constructor subtracts the training cost of the first troll from an empty inventory,
    // then setInventory overwrites it: net effect is just `inv`.
    const nIron = 1 + rng.int(2)
    for (let i = 0; i < nIron; i++) set(randomCell(), IRONCELL)
    const nRock = 1 + rng.int(10)
    for (let i = 0; i < nRock; i++) set(randomCell(), ROCK)
    for (let type = 0; type < 4; type++) {
      const count = 1 + rng.int(3)
      for (let i = 0; i < count; i++) {
        let c = randomCell()
        const t = newTree(g, type, c)
        const ticks = 1 + rng.int(t.growth * (MAX_SIZE + MAX_FRUITS) - 1)
        for (let k = 0; k < ticks; k++) tickTree(t)
        g.trees.push(t)
        treeAt[c] = 1
        const m = mirror(c)
        if (m === c) break
        c = m
        const t2 = newTree(g, type, c)
        for (let k = 0; k < ticks; k++) tickTree(t2)
        g.trees.push(t2)
        treeAt[c] = 1
      }
    }
    if (valid(g)) return g
  }
}

function valid(g: Game): boolean {
  const s0 = g.shack[0]
  if (nearType(g, s0, IRONCELL)) return false
  if (!neighbors(g, s0).some(n => g.grid[n] === GRASS)) return false
  let ironReach = false
  let firstWalk = -1
  for (let c = 0; c < g.W * g.H; c++) {
    if (g.grid[c] === GRASS && firstWalk < 0) firstWalk = c
    if (g.grid[c] === IRONCELL && neighbors(g, c).some(n => g.grid[n] === GRASS)) ironReach = true
  }
  if (!ironReach) return false
  const d = bfs(g, [firstWalk])
  for (let c = 0; c < g.W * g.H; c++) if (g.grid[c] === GRASS && d[c] < 0) return false
  const sd = bfs(g, [s0])
  let opp = 1e9
  for (const n of neighbors(g, g.shack[1])) if (g.grid[n] === GRASS) opp = Math.min(opp, sd[n] + 1)
  return opp <= 16
}

// ---------------------------------------------------------------- inputs

function initInput(g: Game, p: number): string[] {
  const r = [`${g.W} ${g.H}`]
  for (let y = 0; y < g.H; y++) {
    let s = ""
    for (let x = 0; x < g.W; x++) {
      const c = y * g.W + x
      const t = g.grid[c]
      s += t === GRASS ? "." : t === WATER ? "~" : t === IRONCELL ? "+" : t === ROCK ? "#" : c === g.shack[p] ? "0" : "1"
    }
    r.push(s)
  }
  return r
}

function turnInput(g: Game, p: number): string[] {
  const r = [g.inv[p].join(" "), g.inv[1 - p].join(" "), String(g.trees.length)]
  for (const t of g.trees)
    r.push(`${ITEMS[t.type]} ${t.cell % g.W} ${Math.floor(t.cell / g.W)} ${t.size} ${t.health} ${t.fruits} ${t.cooldown}`)
  r.push(String(g.trolls.length))
  for (const u of g.trolls)
    r.push(
      `${u.id} ${u.owner === p ? 0 : 1} ${u.cell % g.W} ${Math.floor(u.cell / g.W)} ${u.speed} ${u.carry} ${u.harvest} ${u.chop} ${u.inv.join(" ")}`,
    )
  return r
}

// ---------------------------------------------------------------- actions

const A_MOVE = 1
const A_HARVEST = 2
const A_PLANT = 3
const A_CHOP = 4
const A_PICK = 5
const A_TRAIN = 6
const A_DROP = 7
const A_MINE = 8

interface Task {
  kind: number
  p: number
  unit: Troll | null
  target: number // MOVE: resolved destination; PLANT / PICK: item type
  talents?: number[]
}

interface ParseResult {
  tasks: Task[]
  errors: string[]
  critical: boolean
}

const treeAtCell = (g: Game, c: number) => {
  for (const t of g.trees) if (t.cell === c && t.health > 0) return t
  return null
}
const nearShack = (g: Game, u: Troll) => u.cell === g.shack[u.owner] || neighbors(g, u.cell).includes(g.shack[u.owner])
const itemIndex = (s: string) => {
  const i = ITEMS.indexOf(s.toUpperCase())
  return i >= 0 ? i : /^\d+$/.test(s) ? parseInt(s) : -1
}

/** Parses one player's output line; `rand` picks among equally good MOVE destinations. */
function parseOutput(g: Game, p: number, line: string, rand: (n: number) => number): ParseResult {
  const res: ParseResult = { tasks: [], errors: [], critical: false }
  const used = new Set<number>()
  for (const raw of line.split(";")) {
    const cmd = raw.trim()
    if (cmd === "" || cmd.toUpperCase() === "WAIT") continue
    if (cmd.toUpperCase().startsWith("MSG ")) continue
    const w = cmd.split(/\s+/)
    const kw = w[0].toUpperCase()
    const kinds: Record<string, [number, number]> = {
      MOVE: [A_MOVE, 4],
      HARVEST: [A_HARVEST, 2],
      PLANT: [A_PLANT, 3],
      CHOP: [A_CHOP, 2],
      PICK: [A_PICK, 3],
      TRAIN: [A_TRAIN, 5],
      DROP: [A_DROP, 2],
      MINE: [A_MINE, 2],
    }
    const k = kinds[kw]
    const argsOk = w.slice(1).every((s, i) => ((kw === "PLANT" || kw === "PICK") && i === 1 ? /^\w+$/.test(s) : /^-?\d+$/.test(s)))
    if (!k || w.length !== k[1] || !argsOk) {
      res.errors.push("Unknown command: " + cmd)
      res.critical = true
      return res
    }
    const task: Task = { kind: k[0], p, unit: null, target: -1 }
    let fail: string | null = null
    if (k[0] === A_TRAIN) {
      const t = w.slice(1).map(Number)
      task.talents = t
      if (t[0] < 1 || t[0] > g.W * g.H) fail = "invalid movement speed"
      if (t[1] < 0 || t[1] > 1000) fail = "invalid carry"
      if (t[2] < 0 || t[2] > MAX_FRUITS) fail = "invalid harvest"
      if (t[3] < 0 || t[3] > 20) fail = "invalid chop"
      if (!fail && !canTrain(g, p, t)) fail = "can't afford"
    } else {
      const id = parseInt(w[1])
      const u = g.trolls.find(t => t.id === id) ?? null
      if (!u) fail = "Troll " + id + " does not exist"
      else if (u.owner !== p) fail = "You don't own troll " + id
      task.unit = u
      if (u && !fail) {
        const tr = treeAtCell(g, u.cell)
        const free = u.carry - sum(u.inv)
        switch (k[0]) {
          case A_MOVE: {
            const x = parseInt(w[2])
            const y = parseInt(w[3])
            if (x < 0 || y < 0 || x >= g.W || y >= g.H) fail = "outside of the board"
            else {
              const opts = nextCells(g, u.cell, y * g.W + x, u.speed)
              task.target = opts[opts.length === 1 ? 0 : rand(opts.length)]
            }
            break
          }
          case A_HARVEST:
            if (!tr) fail = "not at a plant"
            else if (tr.fruits === 0) fail = "no fruits"
            else if (free === 0) fail = "no capacity"
            else if (u.harvest === 0) fail = "no harvest power"
            break
          case A_PLANT: {
            const it = itemIndex(w[2])
            task.target = it
            if (it < 0 || it > BANANA) fail = "not a plant"
            else if (g.grid[u.cell] !== GRASS) fail = "not on grass"
            else if (tr) fail = "existing plant"
            else if (u.inv[it] === 0) fail = "no seed"
            break
          }
          case A_CHOP:
            if (!tr) fail = "not at a plant"
            else if (u.chop === 0) fail = "no chop power"
            break
          case A_PICK: {
            const it = itemIndex(w[2])
            task.target = it
            if (free === 0) fail = "no capacity"
            else if (it < 0 || it > BANANA) fail = "not a plant"
            else if (g.inv[p][it] === 0) fail = "out of stock"
            else if (!nearShack(g, u)) fail = "not next to shack"
            break
          }
          case A_DROP:
            if (sum(u.inv) === 0) fail = "nothing to drop"
            else if (!nearShack(g, u)) fail = "not next to shack"
            break
          case A_MINE:
            if (!nearType(g, u.cell, IRONCELL)) fail = "not next to iron"
            else if (free === 0) fail = "no capacity"
            else if (u.chop === 0) fail = "no chop power"
            break
        }
      }
      if (u && used.has(u.id)) {
        res.errors.push(`Troll ${u.id} already used`)
        continue
      }
      if (u) used.add(u.id)
    }
    if (fail) res.errors.push(`${cmd}: ${fail}`)
    else res.tasks.push(task)
  }
  return res
}

function canTrain(g: Game, p: number, t: number[]): boolean {
  const n = g.trolls.filter(u => u.owner === p).length
  const c = trainCost(n, t)
  for (let i = 0; i < 6; i++) if (c[i] > g.inv[p][i]) return false
  return true
}

function groupByCell(tasks: Task[]): Task[][] {
  const m = new Map<number, Task[]>()
  for (const t of tasks) {
    const c = t.unit!.cell
    if (!m.has(c)) m.set(c, [])
    m.get(c)!.push(t)
  }
  // Cell.getId = x + (y << 16): sort by y then x, i.e. by cell index
  return [...m.entries()].sort((a, b) => a[0] - b[0]).map(e => e[1])
}

function applyMoves(g: Game, moves: Task[]) {
  for (let p = 0; p < 2; p++) {
    const mine = moves.filter(t => t.p === p)
    if (mine.length === 0) continue
    let units = g.trolls.filter(u => u.owner === p)
    let targets = units.map(u => u.cell)
    for (const m of mine) targets[units.indexOf(m.unit!)] = m.target
    const occupied = new Uint8Array(g.W * g.H)
    for (let i = units.length - 1; i >= 0; i--) {
      occupied[units[i].cell] = 1
      if (units[i].cell === targets[i]) {
        units.splice(i, 1)
        targets.splice(i, 1)
      }
    }
    let madeMove = true
    let resolveBlocking = false
    while (madeMove) {
      madeMove = false
      const freq = new Map<number, number>()
      for (const c of targets) freq.set(c, (freq.get(c) ?? 0) + 1)
      for (let i = units.length - 1; i >= 0; i--) {
        const c = targets[i]
        if ((resolveBlocking || freq.get(c) === 1) && !occupied[c]) {
          occupied[c] = 1
          occupied[units[i].cell] = 0
          units[i].cell = c
          units.splice(i, 1)
          targets.splice(i, 1)
          madeMove = true
          resolveBlocking = false
        }
      }
      if (madeMove) continue
      for (let start = 0; start < units.length; start++) {
        const path = [start]
        let looped = false
        for (let i = 0; i < units.length + 1; i++) {
          const target = targets[path[path.length - 1]]
          const idx = units.findIndex(u => u.cell === target)
          if (idx < 0) break
          if (idx === path[0]) {
            looped = true
            break
          }
          path.push(idx)
        }
        if (looped) {
          path.sort((a, b) => a - b)
          for (let i = path.length - 1; i >= 0; i--) {
            const idx = path[i]
            units[idx].cell = targets[idx]
            units.splice(idx, 1)
            targets.splice(idx, 1)
            madeMove = true
          }
        }
      }
      if (!madeMove && !resolveBlocking) {
        resolveBlocking = true
        madeMove = true
      }
    }
    units = []
    targets = []
  }
}

/** Plays one turn with both players' parsed tasks. */
function step(g: Game, tasks: Task[]) {
  const by = (k: number) => tasks.filter(t => t.kind === k)
  applyMoves(g, by(A_MOVE))
  // HARVEST
  for (const grp of groupByCell(by(A_HARVEST))) {
    const tr = treeAtCell(g, grp[0].unit!.cell)!
    for (let i = 1; i <= MAX_FRUITS; i++) {
      if (tr.fruits === 0) break
      for (const t of grp) {
        const u = t.unit!
        if (i > u.harvest || sum(u.inv) >= u.carry) continue
        u.inv[tr.type]++
        if (tr.fruits > 0) tr.fruits--
      }
    }
  }
  // PLANT
  for (const grp of groupByCell(by(A_PLANT))) {
    const types = new Set(grp.map(t => t.target))
    if (types.size !== 1) continue
    for (const t of grp) {
      const u = t.unit!
      u.inv[t.target]--
      if (!treeAtCell(g, u.cell)) g.trees.push(newTree(g, t.target, u.cell))
    }
  }
  // CHOP
  for (const grp of groupByCell(by(A_CHOP))) {
    const tr = treeAtCell(g, grp[0].unit!.cell)
    if (!tr) continue
    for (const t of grp) tr.health = Math.max(tr.health - t.unit!.chop, 0)
    if (tr.health <= 0) {
      let remaining = tr.size
      for (let i = 0; i < tr.size && remaining > 0; i++)
        for (const t of grp) {
          const u = t.unit!
          if (u.carry - sum(u.inv) > 0) {
            u.inv[WOOD]++
            remaining--
          }
        }
    }
  }
  // PICK
  for (const t of by(A_PICK)) {
    if (g.inv[t.p][t.target] > 0) {
      g.inv[t.p][t.target]--
      t.unit!.inv[t.target]++
    }
  }
  // TRAIN
  for (const t of by(A_TRAIN)) {
    if (!canTrain(g, t.p, t.talents!)) continue
    if (g.trolls.some(u => u.cell === g.shack[t.p])) continue
    const n = g.trolls.filter(u => u.owner === t.p).length
    const c = trainCost(n, t.talents!)
    for (let i = 0; i < 6; i++) g.inv[t.p][i] -= c[i]
    const [speed, carry, harvest, chop] = t.talents!
    g.trolls.push({ id: g.nextId++, owner: t.p, cell: g.shack[t.p], speed, carry, harvest, chop, inv: [0, 0, 0, 0, 0, 0] })
  }
  // DROP
  for (const t of by(A_DROP)) {
    const u = t.unit!
    for (let i = 0; i < 6; i++) {
      g.inv[t.p][i] += u.inv[i]
      u.inv[i] = 0
    }
  }
  // MINE
  for (const t of by(A_MINE)) {
    const u = t.unit!
    for (let i = 0; i < u.chop && sum(u.inv) < u.carry; i++) u.inv[IRON]++
  }
  // growth
  for (const t of g.trees) if (t.health > 0) tickTree(t)
  g.trees = g.trees.filter(t => t.health > 0)
  g.turn++
  if (g.turn >= GAME_TURNS || stalled(g)) g.over = true
}

function stalled(g: Game): boolean {
  if (g.trees.length > 0) {
    g.turnsUntilEnd = 0
    const cells = new Set(g.trees.map(t => t.cell))
    const sd = [distFrom(g, g.shack[0]), distFrom(g, g.shack[1])]
    for (const u of g.trolls) {
      if (!cells.has(u.cell)) continue
      g.turnsUntilEnd = Math.max(g.turnsUntilEnd, Math.trunc(sd[u.owner][u.cell] / u.speed) + 6)
    }
    return false
  }
  if (--g.turnsUntilEnd <= 0) return true
  const stuck = [true, true]
  for (const u of g.trolls) if (sum(u.inv) > u.inv[IRON]) stuck[u.owner] = false
  for (let p = 0; p < 2; p++) for (let i = 0; i <= BANANA; i++) if (g.inv[p][i] > 0) stuck[p] = false
  const s = [score(g, 0), score(g, 1)]
  if (stuck[0] && stuck[1]) return true
  if (stuck[0] && s[0] < s[1]) return true
  if (stuck[1] && s[1] < s[0]) return true
  return false
}

// Troll Farm bot: job assignment by rate (points / turns, every job ends with a DROP).
// Jobs: harvest a tree, chop a tree (co-chop to share the wood of a tree an enemy is chopping,
// raid the enemy's young trees), mine iron for training, plant a seed (carried or picked from
// the shack) on a farm cell near the shack, go home and drop. Training follows a design list.
// Candidate training plans, tried by full-game simulation on turn 1 (most promising first).
const PLANS: number[][][] = [
  [[1, 2, 1, 1], [2, 4, 1, 2]],
  [[1, 2, 1, 1], [2, 4, 1, 2], [2, 4, 1, 2]],
  [[2, 4, 1, 2], [2, 4, 1, 2]],
  [[1, 2, 1, 1], [1, 2, 1, 1], [2, 4, 1, 2]],
  [[1, 2, 1, 1], [2, 3, 1, 2], [2, 3, 1, 2]],
  [[1, 2, 1, 1], [1, 2, 1, 2], [1, 2, 1, 2], [1, 2, 1, 2]],
  [[1, 2, 2, 1], [2, 4, 2, 2]],
  [[1, 1, 1, 1], [2, 4, 1, 2], [2, 4, 1, 2]],
  [[1, 2, 1, 1], [2, 3, 1, 2], [2, 4, 1, 2], [2, 4, 1, 2]],
]

/** Game state from our turn input (we are player 0). */
function gameFromInput(init: string[], lines: string[], turnsPlayed: number): Game {
  const [W, H] = init[0].split(" ").map(Number)
  const g: Game = { W, H, grid: new Uint8Array(W * H), shack: [0, 0], inv: [], trees: [], trolls: [], nextId: 0, turn: turnsPlayed, turnsUntilEnd: 0, over: false, dead: [false, false] }
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      const ch = init[1 + y][x]
      const c = y * W + x
      g.grid[c] = ch === "." ? 0 : ch === "~" ? 1 : ch === "#" ? 2 : ch === "+" ? 3 : 4
      if (ch === "0") g.shack[0] = c
      if (ch === "1") g.shack[1] = c
    }
  let i = 0
  g.inv = [lines[i++].split(" ").map(Number), lines[i++].split(" ").map(Number)]
  const nt = +lines[i++]
  for (let k = 0; k < nt; k++) {
    const p = lines[i++].split(" ")
    const type = ITEMS.indexOf(p[0])
    const cell = +p[2] * W + +p[1]
    g.trees.push({ type, cell, size: +p[3], health: +p[4], fruits: +p[5], cooldown: +p[6], growth: 0 })
  }
  for (const t of g.trees) t.growth = COOLDOWN[t.type] - (nearType(g, t.cell, WATER) ? WATER_BOOST[t.type] : 0)
  const nu = +lines[i++]
  for (let k = 0; k < nu; k++) {
    const v = lines[i++].split(" ").map(Number)
    g.trolls.push({ id: v[0], owner: v[1], cell: v[3] * W + v[2], speed: v[4], carry: v[5], harvest: v[6], chop: v[7], inv: v.slice(8, 14) })
    g.nextId = Math.max(g.nextId, v[0] + 1)
  }
  return g
}

/** Our bot playing on from `g` against a passive opponent, resumable across turns (stepped until
 *  a deadline). Selecting training plans this way works as well as with a full opponent, at half
 *  the cost. */
class Sim {
  g: Game
  a: Bot
  horizon = 150
  constructor(g: Game, init: string[], mine: Params, dist: Int16Array[]) {
    this.g = g
    g.dist = dist
    this.a = new Bot(init, mine, true, dist)
    this.a.turnNo = g.turn
  }
  /** Runs until the horizon (returns the value reached) or the deadline (returns null). */
  run(deadline: number): number | null {
    const g = this.g
    while (!g.over && g.turn < this.horizon) {
      if (performance.now() > deadline) return null
      const oa = this.a.turn(turnInput(g, 0))
      step(g, parseOutput(g, 0, oa, () => 0).tasks)
    }
    // score + what our trolls carry (wood 4, fruits 1)
    let v = score(g, 0)
    for (const u of g.trolls) if (u.owner === 0) v += 4 * u.inv[WOOD] + u.inv[0] + u.inv[1] + u.inv[2] + u.inv[3]
    return v
  }
}

interface BTree {
  type: number
  cell: number
  size: number
  health: number
  fruits: number
  cooldown: number
  growth: number
}
interface BTroll {
  id: number
  mine: boolean
  cell: number
  speed: number
  carry: number
  harvest: number
  chop: number
  inv: number[]
  load: number
}

interface Params {
  plan: number[][]
  choosePlan: boolean
  planBudget: number
  planTurnBudget: number
  planTurns: number
  planAll: boolean // evaluate every plan on turn 1 whatever the time (deterministic local tests)
  stick: number
  trainDeadline: number
  plantGamma: number
  sourceValue: number
  farmPerChopper: number
  raidBeta: number
  trainBonus: number
  trollValue: number
  unitMax: number
  seedBonus: number
  denyAlpha: number
  maxWait: number
  patience: number
  wasteLambda: number
}
const DEFAULT_PARAMS: Params = {
  plan: [
    [1, 2, 1, 1],
    [2, 4, 1, 2],
  ],
  choosePlan: true,
  planBudget: 700,
  planTurnBudget: 30,
  planTurns: 12,
  planAll: false,
  stick: 1.3,
  trainDeadline: 180,
  plantGamma: 0.5,
  sourceValue: 12,
  farmPerChopper: 3,
  raidBeta: 0.5,
  trainBonus: 3,
  trollValue: 50,
  unitMax: 12,
  seedBonus: 1,
  denyAlpha: 0.5,
  maxWait: 12,
  patience: 40,
  wasteLambda: 0.7,
}

interface Job {
  u: BTroll
  rate: number
  dest: number // cell to reach (-1: act here)
  act: string // action when at dest
  tree?: BTree
  kind: string
}

class Bot {
  W: number
  H: number
  N: number
  grid: Uint8Array
  shack = -1
  oppShack = -1
  dist: Int16Array[] = []
  dropCells: number[] = []
  dropDist: Int16Array
  oppDropDist: Int16Array
  mineCells: number[] = []
  mineDist: Int16Array
  nearWater: Uint8Array
  turnNo = 0
  P: Params
  seat = 0
  planted = new Set<number>() // cells where we planted
  cost: number[] | null = null
  designs: number[][] = []
  planRef: number[][] | null = null
  targetSince = 0
  lastK = 0
  prev = new Map<number, string>() // troll id -> last job key
  seedIntent = new Map<number, number>() // troll id -> fruit type it picked to plant
  log: string[] = []

  init: string[]
  sim: boolean
  planScores: string = ""
  dbg = 0

  constructor(init: string[], params: Params = DEFAULT_PARAMS, sim = false, dist?: Int16Array[]) {
    this.P = params
    this.init = init
    this.sim = sim
    if (!sim && typeof process !== "undefined") this.dbg = Number(process.env.DBG ?? 0)
    const [W, H] = init[0].split(" ").map(Number)
    this.W = W
    this.H = H
    this.N = W * H
    this.grid = new Uint8Array(this.N)
    for (let y = 0; y < H; y++)
      for (let x = 0; x < W; x++) {
        const ch = init[1 + y][x]
        const c = y * W + x
        this.grid[c] = ch === "." ? GRASS : ch === "~" ? WATER : ch === "#" ? 2 : ch === "+" ? IRONCELL : 4
        if (ch === "0") this.shack = c
        if (ch === "1") this.oppShack = c
      }
    if (dist) this.dist = dist
    else for (let c = 0; c < this.N; c++) this.dist.push(bfs(this, [c]))
    for (const n of this.nbrs(this.shack)) if (this.grid[n] === GRASS) this.dropCells.push(n)
    this.dropDist = bfs(this, this.dropCells)
    const od = this.nbrs(this.oppShack).filter(n => this.grid[n] === GRASS)
    this.oppDropDist = bfs(this, od)
    for (let c = 0; c < this.N; c++)
      if (this.grid[c] === GRASS && this.nbrs(c).some(n => this.grid[n] === IRONCELL)) this.mineCells.push(c)
    this.mineDist = bfs(this, this.mineCells)
    this.nearWater = new Uint8Array(this.N)
    for (let c = 0; c < this.N; c++) if (this.nbrs(c).some(n => this.grid[n] === WATER)) this.nearWater[c] = 1
  }

  nbrs(c: number): number[] {
    const x = c % this.W
    const r: number[] = []
    if (c + this.W < this.N) r.push(c + this.W)
    if (x + 1 < this.W) r.push(c + 1)
    if (c - this.W >= 0) r.push(c - this.W)
    if (x > 0) r.push(c - 1)
    return r
  }

  xy(c: number) {
    return `${c % this.W} ${Math.floor(c / this.W)}`
  }

  steps(u: BTroll, d: number) {
    return d < 0 ? 999 : Math.ceil(d / u.speed)
  }

  /** Tree state after `t` growth ticks. */
  predict(tr: BTree, t: number) {
    let { size, health, fruits, cooldown } = tr
    for (let i = 0; i < t; i++) {
      if (cooldown > 0) cooldown--
      if (cooldown === 0 && health > 0) {
        if (size < MAX_SIZE) {
          size++
          health += DELTA_HEALTH[tr.type]
          cooldown = tr.growth
        } else if (fruits < MAX_FRUITS) {
          fruits++
          cooldown = tr.growth
        } else break
      }
    }
    return { size, health, fruits, cooldown }
  }

  /** Growth ticks until the tree reaches full size (0 if already there). */
  turnsToFull(tr: BTree): number {
    if (tr.size >= MAX_SIZE) return 0
    return (tr.cooldown === 0 ? 1 : tr.cooldown) + (MAX_SIZE - 1 - tr.size) * tr.growth
  }

  /** Turns of chopping (by `power` per turn, the tree growing in between) and the size at death. */
  chopTime(tr: BTree, arrive: number, power: number) {
    let { size, health, cooldown } = this.predict(tr, arrive)
    for (let k = 1; k <= 30; k++) {
      health -= power
      if (health <= 0) return { k, size }
      if (cooldown > 0) cooldown--
      if (cooldown === 0 && size < MAX_SIZE) {
        size++
        health += DELTA_HEALTH[tr.type]
        cooldown = tr.growth
      } else if (cooldown === 0) cooldown = tr.growth
    }
    return { k: 99, size }
  }

  // Training-plan selection: every candidate plan is played out from the turn-1 state (resumable
  // across the first turns, CodinGame being slower than a local run); no training until decided.
  planLines: string[] | null = null
  planIdx = 0
  planSim: Sim | null = null
  planBest = -1e9
  planPending = false
  planLog: string[] = []

  evalPlans(budgetMs: number) {
    const t0 = performance.now()
    while (this.planIdx < PLANS.length) {
      if (!this.planSim) this.planSim = new Sim(gameFromInput(this.init, this.planLines!, 0), this.init, { ...this.P, plan: PLANS[this.planIdx] }, this.dist)
      const v = this.planSim.run(t0 + budgetMs)
      if (v === null) break
      this.planLog.push(`${this.planIdx}:${v}`)
      if (v > this.planBest) {
        this.planBest = v
        this.P = { ...this.P, plan: PLANS[this.planIdx] }
      }
      this.planSim = null
      this.planIdx++
    }
    this.planPending = this.planIdx < PLANS.length && this.turnNo < this.P.planTurns
    this.planScores = `t${this.turnNo} ${this.planLog.join(" ")} (${(performance.now() - t0).toFixed(0)} ms)${this.planPending ? " pending" : ""}`
  }

  turn(lines: string[]): string {
    this.turnNo++
    if (!this.sim && this.P.choosePlan) {
      if (this.turnNo === 1) {
        this.planLines = lines
        this.planPending = true
      }
      if (this.planPending) this.evalPlans(this.P.planAll ? 1e9 : this.turnNo === 1 ? this.P.planBudget : this.P.planTurnBudget)
    }
    const P = this.P
    let li = 0
    const inv = lines[li++].split(" ").map(Number)
    const oppInv = lines[li++].split(" ").map(Number)
    void oppInv
    const nt = parseInt(lines[li++])
    const trees: BTree[] = []
    const treeAt = new Map<number, BTree>()
    for (let i = 0; i < nt; i++) {
      const p = lines[li++].split(" ")
      const type = ITEMS.indexOf(p[0])
      const cell = +p[2] * this.W + +p[1]
      const t: BTree = { type, cell, size: +p[3], health: +p[4], fruits: +p[5], cooldown: +p[6], growth: COOLDOWN[type] - (this.nearWater[cell] ? WATER_BOOST[type] : 0) }
      trees.push(t)
      treeAt.set(cell, t)
    }
    const nu = parseInt(lines[li++])
    const mine: BTroll[] = []
    const opp: BTroll[] = []
    for (let i = 0; i < nu; i++) {
      const v = lines[li++].split(" ").map(Number)
      const u: BTroll = { id: v[0], mine: v[1] === 0, cell: v[3] * this.W + v[2], speed: v[4], carry: v[5], harvest: v[6], chop: v[7], inv: v.slice(8, 14), load: 0 }
      u.load = u.inv.reduce((a, b) => a + b, 0)
      ;(u.mine ? mine : opp).push(u)
      if (this.turnNo === 1 && u.mine && u.id <= 1) this.seat = u.id
    }
    for (const c of [...this.planted]) if (!treeAt.has(c)) this.planted.delete(c)
    for (const [id, t] of [...this.seedIntent]) {
      const u = mine.find(x => x.id === id)
      if (!u || u.inv[t] === 0) this.seedIntent.delete(id)
    }
    const left = 301 - this.turnNo // actions left including this one
    const out: string[] = []
    const dbg = this.dbg

    // ------------------------------------------------------------ training
    const k = mine.length
    const stock = inv.slice()
    let target: number[] | null = null
    let trainNow: number[] | null = null
    if (this.planRef !== P.plan) {
      this.designs = P.plan.map(d => d.slice())
      this.planRef = P.plan
      this.targetSince = this.turnNo
    }
    if (this.lastK !== k) {
      this.lastK = k
      this.targetSince = this.turnNo
    }
    const designs = this.designs
    if (k - 1 < designs.length && this.turnNo < P.trainDeadline && !this.planPending) {
      let d = designs[k - 1]
      let cost = [k + d[0] * d[0], k + d[1] * d[1], k + d[2] * d[2], 0, k + d[3] * d[3]]
      // out of reach for too long (enemy raids, scarce fruit): settle for a cheaper troll
      if (this.turnNo - this.targetSince > P.patience && !cost.every((c, i) => stock[i] >= c)) {
        this.targetSince += P.patience / 2
        const attr = [0, 1, 2, 4] // stock index per attribute
        const minV = [1, 1, 0, 1]
        let bi = -1
        let bd = 0
        for (let a = 0; a < 4; a++) {
          const def = cost[attr[a]] - stock[attr[a]]
          if (d[a] > minV[a] && def > bd) (bd = def), (bi = a)
        }
        if (bi < 0) designs.length = k - 1
        else {
          d = d.slice()
          d[bi]--
          designs[k - 1] = d
          cost = [k + d[0] * d[0], k + d[1] * d[1], k + d[2] * d[2], 0, k + d[3] * d[3]]
        }
      }
      if (k - 1 >= designs.length) this.cost = null
      else if (cost.every((c, i) => stock[i] >= c)) {
        trainNow = d
        for (let i = 0; i < 5; i++) stock[i] -= cost[i]
        // the next design's needs start now
        if (k < designs.length) {
          const d2 = designs[k]
          const c2 = [k + 1 + d2[0] ** 2, k + 1 + d2[1] ** 2, k + 1 + d2[2] ** 2, 0, k + 1 + d2[3] ** 2]
          target = d2
          this.cost = c2
        } else this.cost = null
      } else {
        target = d
        this.cost = cost
      }
    } else this.cost = null
    const need = [0, 0, 0, 0, 0]
    const reserve = [0, 0, 0, 0, 0]
    if (target && this.cost) for (let i = 0; i < 5; i++) {
      need[i] = Math.max(0, this.cost[i] - stock[i])
      reserve[i] = this.cost[i]
    }
    const pickable = [0, 1, 2, 3].map(i => Math.max(0, stock[i] - reserve[i]))

    // ------------------------------------------------------------ values
    const ownTree = (t: BTree) => this.dropDist[t.cell] >= 0 && (this.oppDropDist[t.cell] < 0 || this.dropDist[t.cell] < this.oppDropDist[t.cell])
    const scoreVal = [1, 1, 1, 1]
    // a missing training resource is worth a share of the troll it completes (the scarcest one
    // ends up the most valuable, whatever it is)
    const deficit = need.reduce((a, b) => a + b, 0)
    const unitVal = deficit > 0 ? Math.min(P.unitMax, Math.max(P.trainBonus, P.trollValue / deficit)) : 0
    for (let i = 0; i < 4; i++) if (need[i] > 0) scoreVal[i] += unitVal
    const fruitVal = scoreVal.slice()
    const plantOk = (type: number, cell: number, extra: number) => {
      const g = COOLDOWN[type] - (this.nearWater[cell] ? WATER_BOOST[type] : 0)
      const grow = 1 + 3 * g
      return this.turnNo + extra + grow + Math.ceil(FINAL_HEALTH[type] / 2) + 4 < 300
    }
    const choppers = mine.filter(u => u.chop >= 2 && u.carry >= 3).length
    // farm cells: near the shack, free
    const oppNear = (c: number, r: number) => opp.some(o => this.dist[o.cell][c] >= 0 && this.dist[o.cell][c] <= r)
    const farmCells: number[] = []
    for (let c = 0; c < this.N; c++) {
      if (this.grid[c] !== GRASS || treeAt.has(c) || this.dropDist[c] > 2 || this.dropDist[c] < 0) continue
      if (this.oppDropDist[c] >= 0 && this.oppDropDist[c] <= this.dropDist[c] + 2) continue
      farmCells.push(c)
    }
    farmCells.sort((a, b) => this.dropDist[a] * 2 - this.nearWater[a] * 2 - (this.dropDist[b] * 2 - this.nearWater[b] * 2))
    const farmTrees = trees.filter(t => this.dropDist[t.cell] >= 0 && this.dropDist[t.cell] <= 2 && this.dropDist[t.cell] < this.oppDropDist[t.cell])
    const farmTarget = 2 + P.farmPerChopper * choppers
    let farmMissing = farmTarget - farmTrees.length
    // plant wishes: training-fruit sources first (while trolls remain to train), then farm trees
    const wanted: { type: number; value: number; source: boolean }[] = []
    if (target)
      for (const f of [1, 0, 2]) {
        const have = trees.filter(t => t.type === f && ownTree(t) && this.dropDist[t.cell] <= 3).length
        const want = need[f] >= 10 ? 2 : need[f] >= 4 ? 1 : 0
        if (have < want && stock[f] > 0) wanted.push({ type: f, value: P.sourceValue, source: true })
      }
    if (farmMissing > 0)
      for (const f of [BANANA, 0, 1, 2]) if (need[f] === 0) wanted.push({ type: f, value: 16 * P.plantGamma, source: false })
    if (dbg && this.turnNo >= dbg && this.turnNo < dbg + 3) console.log("  wanted", JSON.stringify(wanted), "farmCells", farmCells.length, "need", need, "stock", stock)
    const seedsAvail = pickable.reduce((a, b) => a + b, 0)
    for (let i = 0; i < 4; i++) if (farmMissing > seedsAvail) fruitVal[i] += P.seedBonus

    const carriedValue = (u: BTroll) => {
      let v = 4 * u.inv[WOOD]
      const intent = this.seedIntent.get(u.id) ?? -1
      for (let i = 0; i < 4; i++) v += (u.inv[i] - (i === intent ? 1 : 0)) * scoreVal[i]
      v += need[4] > 0 ? Math.min(u.inv[IRON], need[4]) * unitVal + Math.max(0, u.inv[IRON] - need[4]) * 0.5 : u.inv[IRON] * 0.5
      return v
    }

    // ------------------------------------------------------------ jobs
    const jobsFor = (u: BTroll): Job[] => {
      const jobs: Job[] = []
      const free = u.carry - u.load
      const cv = carriedValue(u)
      const home = (c: number) => this.steps(u, this.dropDist[c]) + 1
      const dNow = this.dist[u.cell]
      // go home and drop
      const atShack = this.dropDist[u.cell] === 0 || u.cell === this.shack
      if (u.load > 0 && cv > 0) {
        if (atShack) jobs.push({ u, rate: cv, dest: -1, act: `DROP ${u.id}`, kind: "drop" })
        else
          for (const c of this.dropCells) {
            const r = this.steps(u, dNow[c]) + 1
            if (r <= left) jobs.push({ u, rate: cv / r, dest: c, act: `DROP ${u.id}`, kind: "drop" })
          }
      }
      if (free > 0) {
        for (const tr of trees) {
          const d = dNow[tr.cell]
          if (d < 0) continue
          const a = this.steps(u, d)
          const r = home(tr.cell)
          const enemies = opp.filter(o => o.cell === tr.cell)
          // harvest
          if (u.harvest > 0) {
            const f = this.predict(tr, a).fruits
            const g = Math.min(f, free)
            if (g > 0) {
              const ht = Math.ceil(g / u.harvest)
              const T = a + ht + r
              if (T <= left) jobs.push({ u, rate: (cv + g * fruitVal[tr.type]) / T, dest: tr.cell, act: `HARVEST ${u.id}`, tree: tr, kind: "harvest" })
            }
          }
          // chop
          if (u.chop > 0) {
            const eChop = enemies.reduce((s, o) => s + o.chop, 0)
            const own = ownTree(tr)
            const endgame = left < 40
            let wait = 0
            if (own && enemies.length === 0 && !endgame && tr.size < MAX_SIZE) {
              // our growing tree: be there when it reaches full size
              const tm = this.turnsToFull(tr)
              if (tm > P.maxWait) continue
              wait = Math.max(0, tm - a)
            }
            const { k: kk, size } = this.chopTime(tr, a + wait, u.chop + eChop)
            const T = a + wait + kk + r
            if (T > left) continue
            let share = size
            if (enemies.length > 0) share = Math.ceil(size / (1 + enemies.length))
            const wood = Math.min(share, free)
            let value = 4 * wood
            const sizeNow = this.predict(tr, a).size
            if (enemies.length > 0) value += 4 * P.denyAlpha * share
            else if (!own && sizeNow < MAX_SIZE) value += 4 * P.raidBeta * (MAX_SIZE - sizeNow)
            // wood we cannot carry is lost (fine on the enemy's side: that is denial)
            if (enemies.length === 0 && (own || this.dropDist[tr.cell] <= this.oppDropDist[tr.cell])) value -= P.wasteLambda * 4 * Math.max(0, size - wood)
            if (value <= 0) continue
            if (!endgame && own && need[tr.type] > 0 && enemies.length === 0) continue
            const act = wait > 0 && d === 0 ? "" : `CHOP ${u.id}`
            jobs.push({ u, rate: (cv + value) / T, dest: tr.cell, act, tree: tr, kind: "chop" })
          }
        }
        // mine
        if (u.chop > 0 && need[4] > 0) {
          const m = Math.min(free, need[4])
          for (const c of this.mineCells) {
            if (dNow[c] < 0) continue
            const T = this.steps(u, dNow[c]) + Math.ceil(m / u.chop) + home(c)
            if (T <= left) jobs.push({ u, rate: (cv + unitVal * m) / T, dest: c === u.cell ? -1 : c, act: `MINE ${u.id}`, kind: "mine" })
          }
        }
      }
      // plant a carried seed / pick one at the shack
      if ((wanted.length > 0 || this.seedIntent.has(u.id)) && farmCells.length > 0) {
        let seed = -1
        let pick = false
        const intent = this.seedIntent.get(u.id)
        if (intent !== undefined) seed = intent
        else
          for (const w of wanted)
            if (u.inv[w.type] > 0) {
              seed = w.type
              break
            }
        if (seed < 0 && free > 0)
          for (const w of wanted)
            if ((w.source ? stock[w.type] : pickable[w.type]) > 0) {
              seed = w.type
              pick = true
              break
            }
        if (seed >= 0) {
          const w = wanted.find(x => x.type === seed) ?? { type: seed, value: 16 * P.plantGamma, source: false }
          const toShack = pick ? (atShack ? 1 : this.steps(u, this.dropDist[u.cell]) + 1) : 0
          let bestRate = -1
          let bestCell = -1
          for (const c of farmCells) {
            if (oppNear(c, 3)) continue
            const dd = pick ? this.dist[c][this.bestDropFor(c)] : dNow[c]
            const T = toShack + this.steps(u, dd) + 1
            if (!plantOk(seed, c, T)) continue
            const g = COOLDOWN[seed] - (this.nearWater[c] ? WATER_BOOST[seed] : 0)
            const value = w.value * (w.source ? 8 / g : 1) - scoreVal[seed]
            if (value <= 0) continue
            const rate = value / T
            if (rate > bestRate) {
              bestRate = rate
              bestCell = c
            }
          }
          if (bestCell >= 0) {
            if (!pick) jobs.push({ u, rate: bestRate, dest: bestCell, act: `PLANT ${u.id} ${ITEMS[seed]}`, kind: "plant" })
            else if (atShack) jobs.push({ u, rate: bestRate, dest: -1, act: `PICK ${u.id} ${ITEMS[seed]}`, kind: "pick" })
            else for (const dc of this.dropCells) if (dNow[dc] >= 0) jobs.push({ u, rate: bestRate * (1 - 0.05 * dNow[dc]), dest: dc, act: `PICK ${u.id} ${ITEMS[seed]}`, kind: "pick" })
          }
        }
      }
      return jobs
    }

    // greedy assignment
    const assigned = new Map<number, Job>()
    const claimedHarvest = new Map<BTree, number>()
    const claimedChop = new Set<BTree>()
    const all: Job[] = []
    for (const u of mine) all.push(...jobsFor(u))
    for (const j of all) if (this.prev.get(j.u.id) === j.kind + ":" + j.dest) j.rate *= P.stick
    all.sort((a, b) => b.rate - a.rate)
    if (dbg && this.turnNo >= dbg && this.turnNo < dbg + 3)
      for (const u of mine) console.log(`  T${this.turnNo} troll ${u.id}@${this.xy(u.cell)} inv ${u.inv}: ` + all.filter(j => j.u === u).slice(0, 6).map(j => `${j.kind}:${j.dest >= 0 ? this.xy(j.dest) : "here"}:${j.rate.toFixed(2)}`).join(" "))
    let pickedSeeds = 0
    const endCell = new Map<number, number>() // final cell -> troll id
    for (const j of all) {
      if (assigned.has(j.u.id)) continue
      const fin = j.dest < 0 ? j.u.cell : j.dest
      if (endCell.has(fin) && endCell.get(fin) !== j.u.id) continue
      // a destination held by another of our trolls: only once that troll is known to leave it
      if (j.dest >= 0 && j.dest !== j.u.cell) {
        const holder = mine.find(o => o !== j.u && o.cell === j.dest)
        if (holder) {
          const hj = assigned.get(holder.id)
          if (!hj || hj.dest < 0 || hj.dest === holder.cell) continue
        }
      }
      if (j.kind === "harvest" && j.tree) {
        const taken = claimedHarvest.get(j.tree) ?? 0
        if (taken >= j.tree.fruits + 1) continue
        claimedHarvest.set(j.tree, taken + Math.min(j.u.carry - j.u.load, 3))
      }
      if (j.kind === "chop" && j.tree) {
        if (claimedChop.has(j.tree) && !opp.some(o => o.cell === j.tree!.cell)) continue
        claimedChop.add(j.tree)
      }
      if (j.kind === "pick" || j.kind === "plant") {
        if (pickedSeeds >= wanted.length + Math.max(0, farmMissing - 1)) continue
        pickedSeeds++
      }
      assigned.set(j.u.id, j)
      endCell.set(fin, j.u.id)
      this.prev.set(j.u.id, j.kind + ":" + j.dest)
    }
    void farmMissing

    // ------------------------------------------------------------ moves
    const reserved = new Set<number>()
    const acts: [BTroll, string][] = []
    const movers: [BTroll, number][] = []
    for (const u of mine) {
      const j = assigned.get(u.id)
      if (!j) {
        if (u.cell === this.shack) movers.push([u, this.dropCells[0] ?? u.cell])
        else reserved.add(u.cell)
        continue
      }
      if (j.dest < 0 || j.dest === u.cell) {
        if (u.cell === this.shack && trainNow && j.kind !== "drop" && j.kind !== "pick") movers.push([u, this.dropCells[0]])
        else {
          acts.push([u, j.act])
          reserved.add(u.cell)
        }
      } else movers.push([u, j.dest])
    }
    // a troll on the shack blocks training: move it out
    for (const [u, dest] of movers) {
      const c = this.stepToward(u, dest, reserved)
      reserved.add(c)
      if (c !== u.cell) out.push(`MOVE ${u.id} ${this.xy(c)}`)
    }
    for (const [u, a] of acts) {
      if (a === "") continue
      out.push(a)
      if (a.startsWith("PICK")) this.seedIntent.set(u.id, ITEMS.indexOf(a.split(" ")[2]))
    }
    if (trainNow) {
      const shackFree = !mine.some(u => u.cell === this.shack && !movers.some(m => m[0] === u))
      if (shackFree) out.push(`TRAIN ${trainNow.join(" ")}`)
    }
    return out.length ? out.join(";") : "WAIT"
  }

  bestDrop(u: BTroll): number {
    let best = this.dropCells[0]
    for (const c of this.dropCells) if (this.dist[u.cell][c] >= 0 && this.dist[u.cell][c] < this.dist[u.cell][best]) best = c
    return best
  }

  bestDropFor(cell: number): number {
    let best = this.dropCells[0]
    for (const c of this.dropCells) if (this.dist[cell][c] >= 0 && this.dist[cell][c] < this.dist[cell][best]) best = c
    return best
  }

  /** The cell within `speed` steps closest to `dest`, not reserved by another of our trolls. */
  stepToward(u: BTroll, dest: number, reserved: Set<number>): number {
    const d = this.dist[u.cell]
    const td = this.dist[dest]
    let best = u.cell
    let bestD = reserved.has(u.cell) ? 1e9 : td[u.cell] < 0 ? 1e8 : td[u.cell]
    for (let c = 0; c < this.N; c++) {
      if (this.grid[c] !== GRASS || d[c] < 0 || d[c] > u.speed || reserved.has(c)) continue
      const v = td[c] < 0 ? 1e8 : td[c]
      if (v < bestD || (v === bestD && d[c] < d[best])) {
        bestD = v
        best = c
      }
    }
    return best
  }
}

// CodinGame entry point (bundled after engine.ts and bot.ts by build.mjs).
const DUMP = true
const init = [readline()]
const mapH = parseInt(init[0].split(" ")[1])
for (let y = 0; y < mapH; y++) init.push(readline())
const bot = new Bot(init)
let first = true
let lastPlans = ""
for (;;) {
  const lines = [readline(), readline()]
  const nt = parseInt(readline())
  lines.push(String(nt))
  for (let i = 0; i < nt; i++) lines.push(readline())
  const nu = parseInt(readline())
  lines.push(String(nu))
  for (let i = 0; i < nu; i++) lines.push(readline())
  if (DUMP) console.error((first ? init.length + "|" + init.join("|") + "|" : "") + lines.join("|"))
  first = false
  const o = bot.turn(lines)
  if (bot.planScores !== lastPlans) console.error("plans " + (lastPlans = bot.planScores))
  console.log(o)
}

void [PLUM, LEMON, APPLE, BANANA, IRON, WOOD, ITEMS, COOLDOWN, WATER_BOOST, FINAL_HEALTH, DELTA_HEALTH, MAX_SIZE, MAX_FRUITS, GAME_TURNS, GRASS, WATER, ROCK, IRONCELL, SHACK, distFrom, Rng, sum, neighbors, nearType, growthCooldown, newTree, tickTree, bfs, nextCells, trainCost, score, createGame, initInput, turnInput, A_MOVE, A_HARVEST, A_PLANT, A_CHOP, A_PICK, A_TRAIN, A_DROP, A_MINE, parseOutput, canTrain, step, PLANS, gameFromInput, Sim, DEFAULT_PARAMS, Bot]
