// Bundles engine.ts + bot.ts + main.ts into ../spring-challenge-2026-troll-farm.ts (CodinGame takes one file).
// `node build.mjs dump` builds with DUMP = true (full input on stderr, for harness.ts).
import { readFileSync, writeFileSync } from "fs"
const dir = new URL(".", import.meta.url).pathname
const strip = s => s.replace(/^import[\s\S]*?from\s+"[^"]+"\s*\n/gm, "").replace(/^export /gm, "")
const parts = ["engine.ts", "boss5.ts", "valuefeat.ts", "valuemodel.ts", "bot.ts", "main.ts"].map(f => readFileSync(dir + f, "utf8"))
// the Gold boss clone only serves local simulations (simOpp "boss5"): a stub keeps the bundle small
parts[1] =
  "export class Boss5 {\n  turnNo = 0\n  constructor(_init: string[], _dist?: Int16Array[]) {}\n  turn(_lines: string[]): string {\n    return \"WAIT\"\n  }\n  turnGame(_g: Game, _p = 0): string {\n    return \"WAIT\"\n  }\n}\n"
const names = parts
  .slice(0, 5)
  .flatMap(s => [...s.matchAll(/^export (?:const|function|class) (\w+)/gm)].map(m => m[1]))
let main = strip(parts[5])
if (process.argv.includes("dump")) main = main.replace("const DUMP = false", "const DUMP = true")
const ovr = process.argv.find(a => a.startsWith("{"))
if (ovr) main = main.replace("const OVERRIDES = {}", "const OVERRIDES = " + ovr)
const outFile = process.argv.find(a => a.endsWith(".ts")) ?? dir + "../spring-challenge-2026-troll-farm.ts"
const head =
  "// 🎮 CodinGame Multiplayer - spring-challenge-2026-troll-farm\n" +
  "// https://www.codingame.com/multiplayer/bot-programming/spring-challenge-2026-troll-farm\n" +
  "// Generated by troll-farm-tools/build.mjs (engine.ts + bot.ts + main.ts): edit those files.\n"
const out = head + parts.slice(0, 5).map(strip).join("\n") + "\n" + main + `\nvoid [${names.join(", ")}]\n`
writeFileSync(outFile, out)
console.log("written", out.length, "bytes")
